# Generated by Django 3.2.16 on 2023-08-10 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20230810_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Zaza',
        ),
    ]
